# Generated by Django 4.1.7 on 2023-02-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_mail', models.CharField(max_length=100)),
                ('customer_image', models.ImageField(upload_to='customer/')),
                ('customer_password', models.CharField(max_length=15)),
                ('customer_addres', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_first_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='seller/')),
                ('ac_number', models.BigIntegerField()),
                ('ifsc', models.CharField(max_length=20)),
                ('account_holder', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
